#############################################################
# Author: Amila Perera
# File Name: .tmux.conf
#
# Description:
# tmux configuration file
#############################################################

# setting the prefix to C-a
unbind-key C-b
set -g prefix C-a

# enable programs running inside tmux to use C-a
bind-key C-a send-prefix

# sourcing tmux configuration
bind-key r source-file ~/.tmux.conf \; display-message ".tmux.conf Reloaded!"

# act like vim
setw -g mode-keys vi
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection-and-cancel

bind x kill-pane

unbind-key %

# pane splitting
bind-key | split-window -h
bind-key - split-window -v

# remapping movements
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
bind-key -r C-h select-window -t :-
bind-key -r C-l select-window -t :+

# quick window selection
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9

# pane resizing
bind-key -r H resize-pane -L 5
bind-key -r J resize-pane -D 5
bind-key -r K resize-pane -U 5
bind-key -r L resize-pane -R 5

# switch sessions
bind -r ( switch-client -p
bind -r ) switch-client -n

# swap windows
bind-key -n M-Left swap-window -t -1\; select-window -t -1
bind-key -n M-Right swap-window -t +1\; select-window -t +1

# General
set -g default-terminal "xterm-256color"
set -as terminal-overrides ",xterm-256color:RGB"
set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g history-limit 99999
set -g escape-time 0
set -g focus-events on
set -g set-clipboard on
set -g allow-passthrough on
setw -g aggressive-resize on
set -g detach-on-destroy off

# setting status interval
set -g status-interval 5

# setting status bar color
set -g status-fg colour7
set -g status-bg colour8

# setting window list colors
setw -g window-status-current-style fg=white,bg=red,bright

# setting pane divider color
set -g pane-border-style fg=green,bg=black
set -g pane-active-border-style fg=white,bg=black

# setting command line colors
set -g message-style fg=white,bg=black,bright

# customizing status bar
set -g status-left-length 40
set -g status-left " #[fg=colour222,bold]#S #[fg=colour148,nobold]\| #[fg=colour120]${USER}#[fg=7]@#[fg=colour120]#h#[fg=colour148]"
set -g status-right "#[fg=colour120]%a %d-%b-%Y#[fg=colour148] \| #[fg=colour120]%H:%M "

# center window list
set -g status-justify centre
