-- require('telescope').setup {
--   pickers = {
--     find_files = {
--       disable_devicons = true
--     }
--   }
-- }
-- 
-- local builtin = require("telescope.builtin")
-- vim.keymap.set('n', '<leader>f', builtin.find_files, {})
-- vim.keymap.set('n', '<C-t>', builtin.git_files, {})
-- vim.keymap.set('n', '<leader>ps', function()
--   builtin.grep_string({ search = vim.fn.input("Grep > ") })
-- end)
